// Generated by build.py on 2026-09-22T11:59:00Z - do not edit by hand.
// Every node's id equals its index in GRAPH.nodes.
const GRAPH = {
 "meta": {
 "generated": "2026-09-22T11:59:00Z",
 "notesRoot": "notes",
 "noteCount": 30,
 "linkCount": 236,
 "groups": [
  "customers",
  "finance",
  "marketing",
  "operations",
  "people",
  "product",
  "strategy"
 ],
 "excerptChars": 700
},
 "nodes": [
 {
  "id": 0,
  "label": "Customer Feedback Log",
  "group": "customers",
  "file": "notes/customers/customer-feedback-log.md",
  "slug": "customer-feedback-log",
  "excerpt": "Everything a customer says twice gets written down. Reviewed monthly, and it is the least glamorous, most useful document we keep. Recurring themes, ranked by frequency Noise at peak. The room is hard-surfaced and loud from 7:30 to 9. Third most common complaint and the one we have done least about. The queue at 8am. Addressed partly with the double points hour in Loyalty Program to shift demand earlier. Single Origin Ethiopia Guji as espresso. Roughly one in four sends it back. This produced the standing rule to offer a taste first, now in Barista Training Plan. Wanting oat milk at no upcharge. We hold the upcharge, per Pricing Strategy. Not enough seating with power outlets for the…",
  "words": 216,
  "degree": 15
 },
 {
  "id": 1,
  "label": "Regulars and Community",
  "group": "customers",
  "file": "notes/customers/regulars-and-community.md",
  "slug": "regulars-and-community",
  "excerpt": "About 180 people account for a little over half of café revenue. They come in three to six times a week and they are the business. Who they are. The 6:30 crowd, mostly trades and hospital shifts, drip and a morning bun, in and out in four minutes. The 8am commuters, milk drinks, the queue noted in Customer Feedback Log. The 10am freelancers, who stay two hours and want an outlet. The Saturday families, who buy bags and ask about the Farmers Market Booth. What keeps them. Their name, their order remembered, and the same face behind the bar — which makes staff turnover the single biggest risk to this group and the reason for Payroll and Tips Policy and Barista Training Plan. Learning twenty…",
  "words": 240,
  "degree": 12
 },
 {
  "id": 2,
  "label": "Subscription Churn Notes",
  "group": "customers",
  "file": "notes/customers/subscription-churn-notes.md",
  "slug": "subscription-churn-notes",
  "excerpt": "410 active subscribers. 12oz or 2lb, every two or four weeks, shipped or collected. About $7,100 a month combined with retail bags in Monthly PnL Summary. Monthly churn is 6.5%, which means we replace half the book every year. Exit reasons, from cancellation replies: \"Too much coffee\" — 34%. The single biggest cause and entirely a cadence problem, not a product problem. Offering a four week interval before cancelling saves about a third of these. \"Too expensive\" — 21%. Mostly shipping, not coffee, which is a packaging and rate question for Supplier Directory. \"Wanted variety\" — 18%. These people were on default House Blend Ember and never tried Single Origin Ethiopia Guji. Moved away, or no…",
  "words": 222,
  "degree": 18
 },
 {
  "id": 3,
  "label": "Wholesale Accounts",
  "group": "customers",
  "file": "notes/customers/wholesale-accounts.md",
  "slug": "wholesale-accounts",
  "excerpt": "Seven accounts, $12,600 a month, roughly 21% of revenue and the most stable line in Monthly PnL Summary. The book Ledger & Loom (bookshop café) — 18kg a week of House Blend Ember, our largest and oldest account, found us at the Farmers Market Booth. Third Rail Diner — 12kg a week, blend only, price sensitive, never complains. Hartwell Hotel — 9kg a week plus a decaf line, the account that demanded consistency and taught us to log every batch in the Roasting Schedule. Two office contracts, 6kg a week combined, low touch, high margin. Two small cafés at 4kg each, both of which came from the coverage in Local Press Outreach. How it works. Roasted Tuesday, delivered Wednesday morning, net 15…",
  "words": 227,
  "degree": 19
 },
 {
  "id": 4,
  "label": "Cost of Goods Breakdown",
  "group": "finance",
  "file": "notes/finance/cost-of-goods-breakdown.md",
  "slug": "cost-of-goods-breakdown",
  "excerpt": "Blended cost of goods runs 29% of revenue, with a hard ceiling of 32% set in Pricing Strategy. By line Espresso drinks: 18-21%. Milk is the swing factor, not coffee. A 12oz latte carries about $0.34 of House Blend Ember and $0.52 of dairy. Drip and pourover: 12-15%. Best coffee margin in the building. Cold brew on tap: about 18% cost, 82% gross. See Cold Brew Recipe. Retail bags: 42-46%. Thin, but it buys at-home habit and feeds the subscription tracked in Subscription Churn Notes. Pastry: 45% purchase cost from Pastry Partnership, plus waste. At 8% waste the category clears; at 11% it does not. Wholesale: 52-58% depending on tier, per Wholesale Accounts. Hidden costs people forget. Roast…",
  "words": 203,
  "degree": 22
 },
 {
  "id": 5,
  "label": "Equipment Loan Terms",
  "group": "finance",
  "file": "notes/finance/equipment-loan-terms.md",
  "slug": "equipment-loan-terms",
  "excerpt": "Two financed assets, both on the books, both nearly paid down. La Marzocco Linea PB, bought used in year one for $14,500. Five year note at 7.9%, $293 a month, 14 payments remaining. This is the machine whose care is documented in Espresso Machine Maintenance and whose failure closes the café. Loring 12kg roaster, bought in year two for $52,000 with a $12,000 deposit. Seven year equipment note at 6.4%, $947 a month, 41 payments remaining. It is the asset that made Wholesale Accounts possible and it sets the ceiling on how much we can roast per week under the Roasting Schedule. Combined $1,240 a month, carried as a line in Monthly PnL Summary. Terms worth remembering. No prepayment penalty…",
  "words": 229,
  "degree": 8
 },
 {
  "id": 6,
  "label": "Monthly PnL Summary",
  "group": "finance",
  "file": "notes/finance/monthly-pnl-summary.md",
  "slug": "monthly-pnl-summary",
  "excerpt": "Trailing twelve month averages, rounded, so we are arguing about the same numbers. Revenue, $61,400 a month Café, $38,900 Wholesale, $12,600 — see Wholesale Accounts Retail bags and subscription, $7,100 Farmers market, $2,800 — see Farmers Market Booth Costs Cost of goods, $17,800, about 29% of revenue. Detail in Cost of Goods Breakdown. Labour, $22,500, about 37%. Driven by Staff Scheduling Rules and Payroll and Tips Policy. Rent and utilities, $8,900. Equipment loan, $1,240 under Equipment Loan Terms. Marketing, $900, mostly print and market stall fees. Everything else, $4,100. Net, roughly $6,000 a month, or 9.8%. Good for a café, thin for anything with ambitions. The two numbers that…",
  "words": 187,
  "degree": 19
 },
 {
  "id": 7,
  "label": "Pricing Strategy",
  "group": "finance",
  "file": "notes/finance/pricing-strategy.md",
  "slug": "pricing-strategy",
  "excerpt": "We are the second most expensive coffee within a mile and intend to stay there. Cheapest is a race we lose on volume; most expensive invites a comparison we cannot always win. Second is comfortable — the positioning mapped in Competitor Landscape. Current prices: drip $3.50, cortado $4.25, latte $5.25, pourover $6.00, cold brew $5.50, 12oz House Blend Ember $18, 12oz Single Origin Ethiopia Guji $22. Principles we hold to: Raise prices annually by a small amount rather than rarely by a large one. A 4% increase produced no measurable complaint; the 11% jump in year two produced three weeks of them in Customer Feedback Log. Never discount the coffee. Reward frequency instead through Loyalty…",
  "words": 217,
  "degree": 22
 },
 {
  "id": 8,
  "label": "Email Newsletter Strategy",
  "group": "marketing",
  "file": "notes/marketing/email-newsletter-strategy.md",
  "slug": "email-newsletter-strategy",
  "excerpt": "One email every two weeks, Thursday 9am, plain text with one photo. 2,900 subscribers, 41% open rate, 4% click rate. The list comes almost entirely from Loyalty Program signups. Structure that earns the open: One paragraph of something true and specific — a lot arriving, a batch that surprised us, a staffing change. One thing to buy, with a link. Usually the current Single Origin Ethiopia Guji or a subscription. One thing happening — a cupping, a menu change from Seasonal Menu Autumn, the Farmers Market Booth schedule. Email drives subscriptions better than any other channel. It also saves them: the win-back sequence described in Subscription Churn Notes runs from this list and recovers…",
  "words": 214,
  "degree": 16
 },
 {
  "id": 9,
  "label": "Farmers Market Booth",
  "group": "marketing",
  "file": "notes/marketing/farmers-market-booth.md",
  "slug": "farmers-market-booth",
  "excerpt": "Saturday market on Hawthorne, 8am to 1pm, April through October. Two staff, a folding table, a grinder, a hand-pour setup, and about 60 bags of coffee. Direct economics are mediocre. Average market Saturday grosses $780 with roughly $310 of staff and stall cost against it. As a sales channel it barely clears the bar set in Monthly PnL Summary. As an acquisition channel it is the best thing we do. Roughly 30 loyalty signups per market, tracked with a market-specific code from Loyalty Program, and those signups retain better than Instagram signups because they have already tasted the coffee and met a human. What sells: 12oz bags of House Blend Ember to people who have never heard of us, and…",
  "words": 232,
  "degree": 18
 },
 {
  "id": 10,
  "label": "Instagram Content Plan",
  "group": "marketing",
  "file": "notes/marketing/instagram-content-plan.md",
  "slug": "instagram-content-plan",
  "excerpt": "Instagram is our only real acquisition channel and it works because it looks like a coffee bar, not an ad agency. Four posts a week, shot on a phone, natural light only, no stock imagery ever. The rotation: Monday: process. Roasting, cupping, a scale, hands. The Roasting Schedule is quietly the best content generator we have. Wednesday: people. A barista, a regular, the Ivy Street baker from Pastry Partnership. Faces outperform latte art by roughly three to one on saves. Friday: product. Whatever just came off the roaster, usually Single Origin Ethiopia Guji or a bag of House Blend Ember. Sunday: place. The room, the light at 7am, the queue. Stories daily, unpolished, with the menu board…",
  "words": 214,
  "degree": 16
 },
 {
  "id": 11,
  "label": "Local Press Outreach",
  "group": "marketing",
  "file": "notes/marketing/local-press-outreach.md",
  "slug": "local-press-outreach",
  "excerpt": "Three pieces of coverage in three years, all of them from relationships rather than pitches. What worked. A food writer for the weekly tried our coffee at the Farmers Market Booth, asked about the sourcing behind Single Origin Ethiopia Guji, and wrote 800 words about traceability. That piece produced a two-week traffic spike and, more usefully, two of our current Wholesale Accounts. What did not work. A press release. A paid listicle placement. A paid influencer visit that produced one story and no measurable visits, an experiment we will not repeat and which is noted against the marketing line in Monthly PnL Summary. The angle that gets written about is always specific and slightly…",
  "words": 219,
  "degree": 17
 },
 {
  "id": 12,
  "label": "Loyalty Program",
  "group": "marketing",
  "file": "notes/marketing/loyalty-program.md",
  "slug": "loyalty-program",
  "excerpt": "Digital card in the point of sale, no app to download. Ten drinks earns one free drink of equal or lesser value. 1,340 active members, defined as at least one visit in 60 days. What the data says. Members visit 2.4 times a week against 1.3 for non-members and spend 22% more per ticket, mostly because they attach a pastry from Pastry Partnership. The free drink costs us about $0.71 in goods, which is trivial against the visit frequency it buys — the arithmetic is in Cost of Goods Breakdown. Bonus mechanics we actually use: Double points before 7:30am, to thicken the early rush described in Daily Opening Checklist. Bonus points for trying two new drinks at a menu launch, per Seasonal Menu…",
  "words": 219,
  "degree": 18
 },
 {
  "id": 13,
  "label": "Daily Opening Checklist",
  "group": "operations",
  "file": "notes/operations/daily-opening-checklist.md",
  "slug": "daily-opening-checklist",
  "excerpt": "Opening barista arrives at 5:40am. Café doors open at 6:30am sharp — the commuter rush between 7:10 and 8:45 is roughly 40% of weekday transactions, so nothing on this list can slide. Unlock, lights on, music at volume 4 (quiet until 7am). Fire up the La Marzocco. It needs 25 minutes to reach stable brew temperature — start it before anything else. See Espresso Machine Maintenance. Pull and dump two shots, then dial in the current espresso. Target 18g in, 36g out, 27-30 seconds. If the beans are less than 4 days off roast, expect to grind coarser and check the Roasting Schedule for the batch date. Brew the first two batches of filter coffee and log the recipe card. Check the cold brew tap…",
  "words": 223,
  "degree": 9
 },
 {
  "id": 14,
  "label": "Espresso Machine Maintenance",
  "group": "operations",
  "file": "notes/operations/espresso-machine-maintenance.md",
  "slug": "espresso-machine-maintenance",
  "excerpt": "The La Marzocco Linea PB is a three-group machine bought used in year one, financed under the terms in Equipment Loan Terms. It is the most expensive thing in the building and the fastest way to lose a day of trade. Daily, closing shift: backflush every group with water, then with detergent, brush the group heads, soak baskets and portafilters, wipe steam wands and purge them. Grinder hopper emptied and wiped Sunday. Weekly: descale check on the water softener, drain tray deep clean, replace the shower screens if they are pitted, calibrate the grinder against a scale rather than by feel. Quarterly: technician visit. Gaskets, valves, pressure calibration, water filter cartridge. Book it, do…",
  "words": 201,
  "degree": 7
 },
 {
  "id": 15,
  "label": "Green Bean Inventory",
  "group": "operations",
  "file": "notes/operations/green-bean-inventory.md",
  "slug": "green-bean-inventory",
  "excerpt": "Green coffee is our single largest asset and the easiest thing to quietly waste. Count it every Monday morning before the week's plan is set. Current standing lots: Ethiopia Guji, washed, 6 bags (60kg each) — the star of Single Origin Ethiopia Guji. Fast mover, reorder at 3 bags. Colombia Huila, 9 bags — the base of House Blend Ember. Reorder at 5 bags. Brazil Cerrado natural, 7 bags — blend body and the cold brew base. Reorder at 4 bags. Sumatra Mandheling, 2 bags — winter only, do not reorder until October. Swiss Water decaf, 3 bags — wholesale demand only. Storage: pallets off the floor, 60-70°F, under 60% humidity, away from the roaster exhaust wall. Green coffee holds well for about…",
  "words": 212,
  "degree": 16
 },
 {
  "id": 16,
  "label": "Roasting Schedule",
  "group": "operations",
  "file": "notes/operations/roasting-schedule.md",
  "slug": "roasting-schedule",
  "excerpt": "We roast Tuesday and Friday on the 12kg Loring. Two roast days keeps everything the café pulls within a 4-11 day window off roast, which is where our blends taste best. Tuesday is wholesale day. Batches run in this order: House Blend Ember (four batches, 9kg green each), then the decaf, then whatever wholesale single origin is on contract. Bags are labelled, one-way valved, and staged for the Wednesday delivery run described in Wholesale Accounts. Friday is retail and subscription day. Single Origin Ethiopia Guji runs first while the drum is cleanest, then House Blend Ember for the retail shelf, then sample roasts for whatever we are evaluating from the Supplier Directory. Rules we do not…",
  "words": 213,
  "degree": 17
 },
 {
  "id": 17,
  "label": "Supplier Directory",
  "group": "operations",
  "file": "notes/operations/supplier-directory.md",
  "slug": "supplier-directory",
  "excerpt": "Vetted suppliers only. A new supplier needs a sample, a cupping score, and a reference before it gets a purchase order. Green coffee Cascade Importers (Portland) — our main book. Spot lots, 60kg bags, three day delivery, net 30. Best relationship, worst website. Meridian Trading — direct trade Ethiopian and Kenyan lots, higher price, better traceability, the source of Single Origin Ethiopia Guji. Del Valle Brokers — Colombian and Brazilian volume for House Blend Ember. Sharp pricing on 10+ bag orders. Dairy and alternatives Fern Hollow Dairy — whole and oat, Monday and Thursday delivery, non-negotiable on price but never short. Packaging Northline Packaging — valved 12oz bags, cups, lids. 6…",
  "words": 188,
  "degree": 15
 },
 {
  "id": 18,
  "label": "Barista Training Plan",
  "group": "people",
  "file": "notes/people/barista-training-plan.md",
  "slug": "barista-training-plan",
  "excerpt": "Four weeks to the bar alone. Nobody works a rush unsupervised before week three, no exceptions, no matter how experienced the hire. Week one — the room. Open and close, the whole Daily Opening Checklist, the full clean-down in Espresso Machine Maintenance, the till, the pastry count from Pastry Partnership. Tasting: our full menu, including everything on Seasonal Menu Autumn. Week two — coffee. Dialling in to 18g in, 36g out, 27-30 seconds. Grinding by scale, not feel. What House Blend Ember should taste like and what it tastes like when it is stale or under-rested, cross-referenced to the Roasting Schedule. Learn twenty regulars by name, per Regulars and Community. Learn to offer a taste…",
  "words": 224,
  "degree": 18
 },
 {
  "id": 19,
  "label": "Hiring Pipeline",
  "group": "people",
  "file": "notes/people/hiring-pipeline.md",
  "slug": "hiring-pipeline",
  "excerpt": "We hire about four people a year to hold a team of nine. Two are replacements, which is a turnover rate we would like to halve. Process, four steps. A short application, a twenty minute conversation, a paid two hour trial shift on the bar during a real but not peak period, then references. The trial shift decides almost everything. What we look for, in order: warmth with strangers, composure under a queue, willingness to be corrected, and only then coffee experience. Experienced baristas with bad habits take longer to retrain than beginners take to train, a lesson that shaped the four weeks in Barista Training Plan. Where hires come from. Referrals from current staff, which produce the best…",
  "words": 230,
  "degree": 11
 },
 {
  "id": 20,
  "label": "Payroll and Tips Policy",
  "group": "people",
  "file": "notes/people/payroll-and-tips-policy.md",
  "slug": "payroll-and-tips-policy",
  "excerpt": "Base pay starts at $19 an hour and moves to $21 at sign-off under Barista Training Plan, then $23 for shift leads. Roaster is salaried. Everything above minimum is a retention decision, not a generosity decision. Tips are pooled and split by hours worked, including the roaster and the person who worked the Farmers Market Booth. Card tips are paid out with payroll, cash weekly. Pooling is not up for debate — it stops the bar competing for the register and it is why service holds during a rush, per Staff Scheduling Rules. Tips average $4.10 an hour, so effective pay is roughly $23 to $27. That is the number that competes with the shops in Competitor Landscape. Referral bonus of $200 after a…",
  "words": 219,
  "degree": 11
 },
 {
  "id": 21,
  "label": "Staff Scheduling Rules",
  "group": "people",
  "file": "notes/people/staff-scheduling-rules.md",
  "slug": "staff-scheduling-rules",
  "excerpt": "Labour is 37% of revenue in Monthly PnL Summary and it is the number that decides whether a month is good. It is also the number that, cut wrongly, destroys the thing customers actually pay for. Hard rules Two on bar from 7 to 10 on weekdays. The rush between 7:10 and 8:45 in Daily Opening Checklist is 40% of weekday transactions and one person cannot hold it. Opening shift is always someone signed off under Barista Training Plan, never a trainee alone. The Farmers Market Booth Saturday crew is additional headcount, never pulled off the café bar. Roast days are protected. Tuesday and Friday mornings the roaster is not also on bar, per Roasting Schedule. Schedule published 10 days out…",
  "words": 215,
  "degree": 12
 },
 {
  "id": 22,
  "label": "Cold Brew Recipe",
  "group": "product",
  "file": "notes/product/cold-brew-recipe.md",
  "slug": "cold-brew-recipe",
  "excerpt": "Cold brew is 18% of summer revenue and nearly zero labour once the batch is built, which makes it the best margin item on the menu. Concentrate recipe: 1kg coarse ground Brazil Cerrado to 8 litres cold filtered water. Steep 18 hours at cellar temperature, never in the walk-in — cold steeping under 50°F strips the sweetness. Filter through the cloth sock, then a paper polish. Yield is about 7 litres of concentrate. Service: cut 1:1 with water over ice for the tap pour, 1:1.5 for the canned wholesale format. Nitro tap runs at 32 psi on beer gas. Keg lasts three days in summer, five in winter, and gets dumped at day six regardless. Use the Brazil, not the blend. We tested House Blend Ember in…",
  "words": 214,
  "degree": 14
 },
 {
  "id": 23,
  "label": "House Blend Ember",
  "group": "product",
  "file": "notes/product/house-blend-ember.md",
  "slug": "house-blend-ember",
  "excerpt": "Our signature blend and about 55% of everything we roast. If a customer only ever buys one bag from us, it is this one. Recipe: 60% Colombia Huila (washed), 30% Brazil Cerrado (natural), 10% Ethiopia Guji (washed). Medium roast, dropped at 410°F, 16% shrinkage. Tastes like milk chocolate, toasted almond, dried cherry on the finish. Built to hold up in milk without disappearing. Why it works commercially: the Colombia and Brazil are volume lots with stable pricing from Supplier Directory, so the blend cost stays predictable even when specialty prices spike. The 10% Ethiopia is the aroma and the story — it is also the component most at risk when the lot in Green Bean Inventory runs low. It is…",
  "words": 215,
  "degree": 16
 },
 {
  "id": 24,
  "label": "Pastry Partnership",
  "group": "product",
  "file": "notes/product/pastry-partnership.md",
  "slug": "pastry-partnership",
  "excerpt": "We do not bake. We tried for four months in year two and it cost us a staff member and a lot of goodwill. Ivy Street Bakery, three blocks away, now supplies everything in the case. Terms: we buy wholesale at 45% of our retail price, delivered daily at 6:05am, and we carry the waste. Order is placed the previous day by 2pm based on the shift lead's read of the week. Standing order is 24 croissants, 12 almond, 18 morning buns, 10 gluten free, plus a rotating tart. Waste is the whole game. Above 8% waste and the category stops making money. We hit 11% in the first quarter of the deal because we ordered for the weekend we wanted, not the Tuesday we had. Now the order follows the traffic pattern…",
  "words": 220,
  "degree": 14
 },
 {
  "id": 25,
  "label": "Seasonal Menu Autumn",
  "group": "product",
  "file": "notes/product/seasonal-menu-autumn.md",
  "slug": "seasonal-menu-autumn",
  "excerpt": "Autumn menu runs September 15 through November 30. The goal is a reason for regulars to change their order, not novelty for its own sake. On the board: Maple Cortado — house maple syrup, 2oz espresso, 2oz milk. $5.25. Made with House Blend Ember. Spiced Apple Shrub Soda — non-coffee, non-dairy, sells surprisingly well to the afternoon laptop crowd. Guji Pourover flight — three brew ratios of Single Origin Ethiopia Guji side by side, $12, our best educational sell. Sumatra filter returning in November when the winter lot lands per Green Bean Inventory. We are dropping the pumpkin latte. It sold, but it sold instead of espresso drinks and it needed a syrup we do not otherwise use…",
  "words": 209,
  "degree": 18
 },
 {
  "id": 26,
  "label": "Single Origin Ethiopia Guji",
  "group": "product",
  "file": "notes/product/single-origin-ethiopia-guji.md",
  "slug": "single-origin-ethiopia-guji",
  "excerpt": "Washed Ethiopia from the Guji zone, 1,950-2,100 metres, heirloom varietals, sourced through Meridian Trading in the Supplier Directory. Cupped at 87.5. Roast: light, dropped at 396°F, no development past 18%. Roasted first on Friday when the drum is cleanest, per the Roasting Schedule. Tasting: jasmine, bergamot, white peach, a clean tea-like body. Brews beautifully as pourover and V60, which is why it anchors the filter menu. As espresso it is polarising — bright and floral, and roughly one in four customers sends it back. Baristas should offer a taste before selling it as a shot, a rule that came directly out of complaints in Customer Feedback Log. This is our highest-margin bag at $22…",
  "words": 200,
  "degree": 16
 },
 {
  "id": 27,
  "label": "Competitor Landscape",
  "group": "strategy",
  "file": "notes/strategy/competitor-landscape.md",
  "slug": "competitor-landscape",
  "excerpt": "Four coffee businesses within a mile. Knowing precisely what each is good at is more useful than pretending we beat all of them. Bluewater Coffee (two blocks). A regional chain, cheaper by about 15%, faster, open at 5:30am, and consistently mediocre. They win the pure commuter who wants speed. We do not compete on speed; we compete on the 8am customer who will wait four minutes, per Regulars and Community. Fathom Roasters (half a mile). The most respected roaster in the city, more expensive than us, wholesale-first, minimal café. They are the reason we sit second on price rather than first, per Pricing Strategy, and they are the real competition for the accounts in Wholesale Accounts. The…",
  "words": 230,
  "degree": 14
 },
 {
  "id": 28,
  "label": "Quarterly OKRs",
  "group": "strategy",
  "file": "notes/strategy/quarterly-okrs.md",
  "slug": "quarterly-okrs",
  "excerpt": "Three objectives, no more. Anything not on this page is maintenance. Objective 1 — make wholesale the stable half of the business. Grow Wholesale Accounts from $12,600 to $16,000 a month. Land two accounts, at least one from the canned product in Cold Brew Recipe. Zero consistency incidents, meaning zero improvised blends of House Blend Ember during a stockout, which requires the reorder discipline in Green Bean Inventory. Objective 2 — stop leaking subscribers. Cut monthly churn from 6.5% to 4.5%, per Subscription Churn Notes. Offer a cadence change at every cancellation. Put a rotating single origin, usually Single Origin Ethiopia Guji, in front of every subscriber past their third…",
  "words": 204,
  "degree": 25
 },
 {
  "id": 29,
  "label": "Second Location Analysis",
  "group": "strategy",
  "file": "notes/strategy/second-location-analysis.md",
  "slug": "second-location-analysis",
  "excerpt": "The question we keep circling. Honest answer today: not yet, and here is what would change it. The case for. The Loring has headroom — about 96kg of green a week across two roast days per Equipment Loan Terms — so a second café would be supplied by an asset we already own. Brand awareness from Instagram Content Plan and Local Press Outreach extends past the neighbourhood we actually trade in. The case against, in order of seriousness. People. A second bar needs a shift lead we do not have and a hiring pipeline running at roughly double its current rate, per Hiring Pipeline and Barista Training Plan. Cash. Net is about $6,000 a month in Monthly PnL Summary. Build-out is $180,000 to $240,000…",
  "words": 225,
  "degree": 19
 }
],
 "links": [
 {
  "source": 0,
  "target": 1,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 0,
  "target": 2,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 0,
  "target": 4,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 0,
  "target": 7,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 0,
  "target": 8,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 0,
  "target": 12,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 0,
  "target": 14,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 0,
  "target": 15,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 0,
  "target": 18,
  "kind": "wikilink",
  "weight": 6
 },
 {
  "source": 0,
  "target": 20,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 0,
  "target": 21,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 0,
  "target": 23,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 0,
  "target": 25,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 0,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 0,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 1,
  "target": 8,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 1,
  "target": 9,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 1,
  "target": 11,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 1,
  "target": 12,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 1,
  "target": 18,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 1,
  "target": 19,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 1,
  "target": 20,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 1,
  "target": 24,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 1,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 1,
  "target": 27,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 1,
  "target": 29,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 2,
  "target": 3,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 2,
  "target": 4,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 2,
  "target": 6,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 2,
  "target": 7,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 2,
  "target": 8,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 2,
  "target": 9,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 2,
  "target": 10,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 2,
  "target": 12,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 2,
  "target": 15,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 2,
  "target": 17,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 2,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 2,
  "target": 24,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 2,
  "target": 25,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 2,
  "target": 26,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 2,
  "target": 27,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 2,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 2,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 3,
  "target": 4,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 3,
  "target": 5,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 6,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 3,
  "target": 7,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 3,
  "target": 8,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 9,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 10,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 3,
  "target": 11,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 12,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 3,
  "target": 15,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 3,
  "target": 16,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 17,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 3,
  "target": 19,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 3,
  "target": 22,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 3,
  "target": 27,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 3,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 3,
  "target": 29,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 5,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 4,
  "target": 6,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 7,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 8,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 4,
  "target": 9,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 4,
  "target": 10,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 4,
  "target": 12,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 13,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 4,
  "target": 15,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 4,
  "target": 16,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 4,
  "target": 17,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 18,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 4,
  "target": 22,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 23,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 4,
  "target": 24,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 4,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 4,
  "target": 26,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 4,
  "target": 28,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 4,
  "target": 29,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 5,
  "target": 6,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 5,
  "target": 14,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 5,
  "target": 16,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 5,
  "target": 17,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 5,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 5,
  "target": 29,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 7,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 9,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 11,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 6,
  "target": 12,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 6,
  "target": 14,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 15,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 17,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 6,
  "target": 19,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 6,
  "target": 20,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 21,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 22,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 6,
  "target": 24,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 6,
  "target": 27,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 6,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 6,
  "target": 29,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 7,
  "target": 8,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 7,
  "target": 9,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 7,
  "target": 10,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 7,
  "target": 11,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 7,
  "target": 12,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 7,
  "target": 15,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 7,
  "target": 16,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 7,
  "target": 17,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 7,
  "target": 20,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 7,
  "target": 22,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 7,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 7,
  "target": 24,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 7,
  "target": 25,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 7,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 7,
  "target": 27,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 7,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 7,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 8,
  "target": 9,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 8,
  "target": 10,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 8,
  "target": 11,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 8,
  "target": 12,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 8,
  "target": 15,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 8,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 8,
  "target": 26,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 8,
  "target": 27,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 8,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 8,
  "target": 29,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 9,
  "target": 10,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 9,
  "target": 11,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 9,
  "target": 12,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 9,
  "target": 20,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 9,
  "target": 21,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 9,
  "target": 23,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 9,
  "target": 25,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 9,
  "target": 26,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 9,
  "target": 27,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 9,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 9,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 10,
  "target": 11,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 10,
  "target": 12,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 10,
  "target": 16,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 10,
  "target": 18,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 10,
  "target": 22,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 10,
  "target": 23,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 10,
  "target": 24,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 10,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 10,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 10,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 11,
  "target": 12,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 11,
  "target": 15,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 11,
  "target": 16,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 11,
  "target": 18,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 11,
  "target": 21,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 11,
  "target": 24,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 11,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 11,
  "target": 27,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 11,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 11,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 12,
  "target": 13,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 12,
  "target": 17,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 12,
  "target": 23,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 12,
  "target": 24,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 12,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 12,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 12,
  "target": 29,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 13,
  "target": 14,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 13,
  "target": 15,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 13,
  "target": 16,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 13,
  "target": 18,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 13,
  "target": 21,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 13,
  "target": 22,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 13,
  "target": 24,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 14,
  "target": 16,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 14,
  "target": 18,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 14,
  "target": 21,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 15,
  "target": 16,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 15,
  "target": 17,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 15,
  "target": 22,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 15,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 15,
  "target": 25,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 15,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 15,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 16,
  "target": 17,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 16,
  "target": 18,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 16,
  "target": 21,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 16,
  "target": 22,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 16,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 16,
  "target": 25,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 16,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 16,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 17,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 17,
  "target": 24,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 17,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 17,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 17,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 17,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 18,
  "target": 19,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 18,
  "target": 20,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 18,
  "target": 21,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 18,
  "target": 22,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 18,
  "target": 23,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 18,
  "target": 24,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 18,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 18,
  "target": 26,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 18,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 18,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 19,
  "target": 20,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 19,
  "target": 21,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 19,
  "target": 22,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 19,
  "target": 25,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 19,
  "target": 27,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 19,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 19,
  "target": 29,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 20,
  "target": 21,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 20,
  "target": 27,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 20,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 20,
  "target": 29,
  "kind": "wikilink",
  "weight": 3
 },
 {
  "source": 21,
  "target": 24,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 21,
  "target": 28,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 22,
  "target": 23,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 22,
  "target": 25,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 22,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 22,
  "target": 29,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 23,
  "target": 25,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 23,
  "target": 26,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 23,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 24,
  "target": 27,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 24,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 25,
  "target": 26,
  "kind": "wikilink",
  "weight": 4
 },
 {
  "source": 25,
  "target": 28,
  "kind": "shared",
  "weight": 1
 },
 {
  "source": 26,
  "target": 27,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 26,
  "target": 28,
  "kind": "wikilink",
  "weight": 2
 },
 {
  "source": 27,
  "target": 28,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 27,
  "target": 29,
  "kind": "wikilink",
  "weight": 5
 },
 {
  "source": 28,
  "target": 29,
  "kind": "wikilink",
  "weight": 5
 }
]
};
if (typeof window !== 'undefined') { window.GRAPH = GRAPH; }
