// Generated by build.py on 2026-09-28T17:31:08Z - do not edit by hand.
// Every node's id equals its index in GRAPH.nodes.
const GRAPH = {
 "meta": {
 "generated": "2026-09-28T17:31:08Z",
 "notesRoot": "notes",
 "noteCount": 23,
 "linkCount": 0,
 "groups": [
  "captures",
  "census",
  "unfiled"
 ],
 "excerptChars": 700
},
 "nodes": [
 {
  "id": 0,
  "label": "Meeting 2026 09 27 1359",
  "group": "unfiled",
  "file": "notes/Meeting-2026-09-27-1359.md",
  "slug": "meeting-2026-09-27-1359",
  "excerpt": "Minutes taken Sunday 27 September 2026 at 13:59 by the Scribe. Attendees Not named in the recording. Key Decisions \"plant my tree, Monday 28th September. at 5 0 0 p.m. 30 minutes the ... default since no end was given\" — confirmed with \"Yes\" and \"Written into Google calendar\". Action Items owner not stated - \"plant my tree\" calendar entry, written into Google calendar - \"Monday 28 September at 5 0 0 p.m.\" Raw Excerpts Can you remind me to pla- to my tree at 5 p.m. tomorrow. would be plant my tree, Monday 28th September. All since no end was given, sir. written into your Google calendar. Shall I put it in? Written into Google calendar plant my tree Monday 20 8 September at 5 0 0 p.m…",
  "words": 140,
  "degree": 0,
  "touched": 1790497787
 },
 {
  "id": 1,
  "label": "Am Building to Help Me in My Day",
  "group": "captures",
  "file": "notes/captures/am-building-to-help-me-in-my-day.md",
  "slug": "am-building-to-help-me-in-my-day",
  "excerpt": "Captured Monday 28 September 2026 at 17:22. I am building to help me in my day to day task and help me earn real money for me.",
  "words": 27,
  "degree": 0,
  "touched": 1790596345
 },
 {
  "id": 2,
  "label": "Am Building You to Make Me Real Money",
  "group": "captures",
  "file": "notes/captures/am-building-you-to-make-me-real-money.md",
  "slug": "am-building-you-to-make-me-real-money",
  "excerpt": "Captured Monday 28 September 2026 at 17:12. I am building you to make me real money when I relax and you do the work will you remember this for your life time.",
  "words": 32,
  "degree": 0,
  "touched": 1790595758
 },
 {
  "id": 3,
  "label": "Am Your Boss and Remember My Voice for",
  "group": "captures",
  "file": "notes/captures/am-your-boss-and-remember-my-voice-for.md",
  "slug": "am-your-boss-and-remember-my-voice-for",
  "excerpt": "Captured Monday 28 September 2026 at 21:05. I am your boss and remember my voice for Lifetime.",
  "words": 17,
  "degree": 0,
  "touched": 1790609708
 },
 {
  "id": 4,
  "label": "Passport Renews in March",
  "group": "captures",
  "file": "notes/captures/passport-renews-in-march.md",
  "slug": "passport-renews-in-march",
  "excerpt": "Captured Monday 28 September 2026 at 23:00. My passport renews in March.",
  "words": 12,
  "degree": 0,
  "touched": 1790616625
 },
 {
  "id": 5,
  "label": "You Have to Learn My Voice",
  "group": "captures",
  "file": "notes/captures/you-have-to-learn-my-voice.md",
  "slug": "you-have-to-learn-my-voice",
  "excerpt": "Captured Monday 28 September 2026 at 21:04. You have to learn my voice.",
  "words": 13,
  "degree": 0,
  "touched": 1790609661
 },
 {
  "id": 6,
  "label": "How I Sign My Mail",
  "group": "census",
  "file": "notes/census/how-i-sign-my-mail.md",
  "slug": "how-i-sign-my-mail",
  "excerpt": "Captured Monday 28 September 2026 at 22:35. Sincerely, Aditya Sir. Asked in the Census, under People & Work: \"When I write on your behalf, how should the letter be signed?\"",
  "words": 30,
  "degree": 0,
  "touched": 1790615149
 },
 {
  "id": 7,
  "label": "My Birthday and Birthplace",
  "group": "census",
  "file": "notes/census/my-birthday-and-birthplace.md",
  "slug": "my-birthday-and-birthplace",
  "excerpt": "Captured Monday 28 September 2026 at 22:25. 19-04-1999 and born in begusarai Bihar. Asked in the Census, under Life: \"When is your birthday, and where were you born?\"",
  "words": 28,
  "degree": 0,
  "touched": 1790614548
 },
 {
  "id": 8,
  "label": "My Clients and Partners",
  "group": "census",
  "file": "notes/census/my-clients-and-partners.md",
  "slug": "my-clients-and-partners",
  "excerpt": "Captured Monday 28 September 2026 at 22:34. No Clients. Asked in the Census, under People & Work: \"Which clients or partners matter most at the moment?\"",
  "words": 26,
  "degree": 0,
  "touched": 1790615086
 },
 {
  "id": 9,
  "label": "My Company",
  "group": "census",
  "file": "notes/census/my-company.md",
  "slug": "my-company",
  "excerpt": "Captured Monday 28 September 2026 at 22:33. Ever-Commerce build AI agents for website. Asked in the Census, under People & Work: \"What is the company called, and what does it actually do?\"",
  "words": 32,
  "degree": 0,
  "touched": 1790614995
 },
 {
  "id": 10,
  "label": "My Daily Rhythm",
  "group": "census",
  "file": "notes/census/my-daily-rhythm.md",
  "slug": "my-daily-rhythm",
  "excerpt": "Captured Monday 28 September 2026 at 22:27. Like I work as a Full Stack Developer So I live alone so in weekday looks like built you my Galaxy. Asked in the Census, under Life: \"What does an ordinary weekday look like - when do you start, and when do you stop?\"",
  "words": 51,
  "degree": 0,
  "touched": 1790614674
 },
 {
  "id": 11,
  "label": "My Household",
  "group": "census",
  "file": "notes/census/my-household.md",
  "slug": "my-household",
  "excerpt": "Captured Monday 28 September 2026 at 22:26. I have two younger brother name Sanu & Vivek I live with my parents. Asked in the Census, under Life: \"Who lives with you, and what should I know about them?\"",
  "words": 38,
  "degree": 0,
  "touched": 1790614619
 },
 {
  "id": 12,
  "label": "My Name",
  "group": "census",
  "file": "notes/census/my-name.md",
  "slug": "my-name",
  "excerpt": "Captured Monday 28 September 2026 at 21:19. Aditya's Sir. Asked in the Census, under Life: \"What is your full name, and what should I call you?\"",
  "words": 26,
  "degree": 0,
  "touched": 1790610544
 },
 {
  "id": 13,
  "label": "My Schooling",
  "group": "census",
  "file": "notes/census/my-schooling.md",
  "slug": "my-schooling",
  "excerpt": "Captured Monday 28 September 2026 at 22:36. I am graduate done B.Tech from haldia institute of Technology. Asked in the Census, under Education & Study: \"Where did you go to school?\"",
  "words": 31,
  "degree": 0,
  "touched": 1790615181
 },
 {
  "id": 14,
  "label": "My Work and Title",
  "group": "census",
  "file": "notes/census/my-work-and-title.md",
  "slug": "my-work-and-title",
  "excerpt": "Captured Monday 28 September 2026 at 22:32. I am Full Stack Developer I build real AI agents for help in day to day life and make task easy. Asked in the Census, under People & Work: \"What do you do, and what is your title?\"",
  "words": 45,
  "degree": 0,
  "touched": 1790614940
 },
 {
  "id": 15,
  "label": "The Languages I Speak",
  "group": "census",
  "file": "notes/census/the-languages-i-speak.md",
  "slug": "the-languages-i-speak",
  "excerpt": "Captured Monday 28 September 2026 at 22:37. Hindi & English Proficient. Asked in the Census, under Education & Study: \"Which languages do you speak, and how well?\"",
  "words": 27,
  "degree": 0,
  "touched": 1790615244
 },
 {
  "id": 16,
  "label": "The People I Work with",
  "group": "census",
  "file": "notes/census/the-people-i-work-with.md",
  "slug": "the-people-i-work-with",
  "excerpt": "Captured Monday 28 September 2026 at 22:34. I work most closely with you. Asked in the Census, under People & Work: \"Who do you work with most closely, and what does each of them do?\"",
  "words": 35,
  "degree": 0,
  "touched": 1790615041
 },
 {
  "id": 17,
  "label": "What I Am Learning Now",
  "group": "census",
  "file": "notes/census/what-i-am-learning-now.md",
  "slug": "what-i-am-learning-now",
  "excerpt": "Captured Monday 28 September 2026 at 22:37. Agentic AI & building You. Asked in the Census, under Education & Study: \"What are you learning at the moment?\"",
  "words": 27,
  "degree": 0,
  "touched": 1790615222
 },
 {
  "id": 18,
  "label": "What I Am Reading",
  "group": "census",
  "file": "notes/census/what-i-am-reading.md",
  "slug": "what-i-am-reading",
  "excerpt": "Captured Monday 28 September 2026 at 22:38. Agentic AI and after goal to build & train LLM Model. Asked in the Census, under Education & Study: \"What are you reading, and what is next after it?\"",
  "words": 36,
  "degree": 0,
  "touched": 1790615281
 },
 {
  "id": 19,
  "label": "What I Am Working on",
  "group": "census",
  "file": "notes/census/what-i-am-working-on.md",
  "slug": "what-i-am-working-on",
  "excerpt": "Captured Monday 28 September 2026 at 22:35. N/A. Asked in the Census, under People & Work: \"What are you working on right now, and what is the deadline on it?\"",
  "words": 30,
  "degree": 0,
  "touched": 1790615101
 },
 {
  "id": 20,
  "label": "What I Studied",
  "group": "census",
  "file": "notes/census/what-i-studied.md",
  "slug": "what-i-studied",
  "excerpt": "Captured Monday 28 September 2026 at 22:36. B.Tech Computer Science at HIT. Asked in the Census, under Education & Study: \"What did you study after school, and where?\"",
  "words": 28,
  "degree": 0,
  "touched": 1790615203
 },
 {
  "id": 21,
  "label": "Where I Live",
  "group": "census",
  "file": "notes/census/where-i-live.md",
  "slug": "where-i-live",
  "excerpt": "Captured Monday 28 September 2026 at 22:24. I live in Noida but my hometown is Dhanbad Jharkhand I use India clock. Asked in the Census, under Life: \"Where do you live, and which clock do you keep?\"",
  "words": 37,
  "degree": 0,
  "touched": 1790614470
 },
 {
  "id": 22,
  "label": "Why I Am Building You",
  "group": "census",
  "file": "notes/census/why-i-am-building-you.md",
  "slug": "why-i-am-building-you",
  "excerpt": "Captured Monday 28 September 2026 at 22:31. I am building you as my personal Assistant who goal to earn real money for me using the internet and generate me real revenue who should be capable of today all task as a human need and as much intelligent who learn daily a new thing every hour and a powerful AI who can do all task what his owner told to do and you should be capable of doing all my task in my day to day life. Asked in the Census, under Life: \"Why are you building me, and what should I be for?\"",
  "words": 103,
  "degree": 0,
  "touched": 1790614865
 }
],
 "links": []
};
if (typeof window !== 'undefined') { window.GRAPH = GRAPH; }
